#!/bin/bash

echo "CONDA_DIR=${CONDA_DIR}" >> .Renviron

# See https://jira-secure.berkeley.edu/browse/DH-305
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
export XDG_CONFIG_HOME=${REPO_DIR}/rstudio-config
exec "$@"
